# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
namespace: tp7-kustomize

  # On garde `images:` pour piloter le tag depuis l'overlay (démonstration rollout)
  # Ici on ne change pas le repository, seulement la version (newTag)
images:
- name: ghcr.io/anaismorvan/spring-petclinic
  newName: ghcr.io/anaismorvan/spring-petclinic
  newTag: 4.1.0-SNAPSHOT
- name: spring-petclinic
  newName: ghcr.io/anaismorvan/spring-petclinic
  newTag: 7394ad7f2db512226a72457dd6caf643e2945c4f

resources:
- ../../base
patches:
- path: patch-routing.yml
- path: replicas.yml
  target:
    kind: Deployment
    name: clinic-deploy
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
