# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
namespace: tp7-kustomize

images:
  # On garde `images:` pour piloter le tag depuis l'overlay (démonstration rollout)
  # Ici on ne change pas le repository, seulement la version (newTag)
  - name: ghcr.io/anaismorvan/spring-petclinic
    newName: ghcr.io/anaismorvan/spring-petclinic
    newTag: 4.1.0-SNAPSHOT

resources:
  - ../../base
patches:
  - path: patch-routing.yml
  - path: replicas.yml
    target:
      kind: Deployment
      name: clinic-deploy
